from config.config import (
    NEWSAPI_KEYS, NEWSDATAAPI_KEY, LANGUAGES, PAGE_SIZE, HOURS_PERIOD, QUERY,
    PAGE, RAW_NEWS_TOPIC, FILTERED_NEWS_TOPIC, PROCESSED_NEWS_TOPIC, 
    INTERACTIONS_TOPIC, NULL_REPLACEMENTS, KAFKA_BOOTSTRAP_SERVERS, SPARK_VERSION
)
